platform :ios, '9.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseCallKitUI' do

    pod 'Hyphenate'
    pod 'Masonry'
    pod 'AgoraRtcEngine_iOS'
    pod 'SDWebImage', '~> 3.7.2'

end